MVCAPPTAG/MVCAPPTAG/Models/Book.cs
namespace MVCAPPTAG.Models
{
    public class Book
    {
        public int BookID { set; get; }
        public String? Title { set; get; }
        public float Cost { set; get; }
        public String? AuthorName { set; get; }
    }
}

MVCAPPTAG/MVCAPPTAG/Models/ErrorViewModel.cs
namespace MVCAPPTAG.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCAPPTAG/MVCAPPTAG/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAPPTAG.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public int Add(int x, int y) 
        {
            return x + y;
        }
        public int Subtract(int x, int y)
        {
            return x-y;
        }
        public int Multiply(int x, int y)
        {
            return x*y;
        }
    }
}

MVCAPPTAG/MVCAPPTAG/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCAPPTAG.Models;
using System.Diagnostics;
using System.Text;

namespace MVCAPPTAG.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;
        public HomeController(ILogger<HomeController> logger,IConfiguration configuration)
        {
            _configuration= configuration;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(int x, IFormCollection Collection)
        {
            StringBuilder data = new StringBuilder(500);
            data.Append("x:");
            data.Append(x);
            data.Append(" ");
            data.Append("name:");
            data.Append(Collection["name"]);
            data.Append(" ");
            data.Append("password:");
            data.Append(Collection["Password"]);
            //foreach (var item in Collection) 
            //{
            //    data.Append(item.Key);
            //    data.Append(':');
            //    data.Append(item.Value);
            //    data.Append(" ");
            //}
            ViewData["x"] = data.ToString();
            return View("IndexPost");
        }
        public ActionResult DoTask(int? id)
        {
            if (id.HasValue)
            {
                ViewData["id"] = id.Value;
            }
            else
            {
                ViewData["id"] = 0;
            }
            return View();
        }
        public ActionResult Test()
        {
            return RedirectToAction("Index");
        }
        public ActionResult GetBook()
        {
            Book b1 = new Book() { AuthorName = "H Lee" };
            ViewData["book"] = b1;
            return View();
        }
        [ResponseCache(Duration = 15)]
        public IActionResult GetTime()
        {
            String todate = DateTime.Now.ToLongTimeString();
            ViewData["date"] = todate;
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Menu()
        {
            string conString = _configuration.GetConnectionString("DefaultConnection");
            _logger.Log(LogLevel.Information, conString);
            return View();
        }
        public IActionResult Echo(string name,string city)
        {   
            String s1 ="user" + name + "From City=" + city;
            ViewData.Add("Data1", s1);
            return View();
        }
        public IActionResult SayHello(string name)
        {
            String s1 = ("Hello" + name);
            ViewData.Add("Data1", s1);
            return View("Echo");
        }
    }
}

MVCAPPTAG/MVCAPPTAG/Controllers/PartialViewController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAPPTAG.Controllers
{
    public class PartialViewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Tabs()
        {
            ViewData["data1"] = "Tom and Jerry are Good friends";
            return View();
        }
    }
}

MVCAPPTAG/MVCAPPTAG/Controllers/SamlpleController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCAPPTAG.Controllers
{
    public class SamlpleController : Controller
    {
        public IActionResult Start()
        {
            return View();
        }
    }
}

MVCAPPTAG/MVCAPPTAG/Views/Home/DoTask.cshtml
@{
    ViewData["Title"] = "DoTask";
}

<h1>DoTask</h1>

<h1>ViewData:@ViewData["id"]</h1>

MVCAPPTAG/MVCAPPTAG/Views/Home/Echo.cshtml
@{
    ViewData["Title"] = "Echo";
   
}

<h1>Echo</h1>
<h1>@ViewData["Data1"]</h1>

MVCAPPTAG/MVCAPPTAG/Views/Home/GetBook.cshtml
@using MVCAPPTAG.Models;
@{
    ViewData["Title"] = "GetBook";
}
<h1>GetBook</h1>
<div>
    @{
        Book b1 = (Book) ViewData["Book"];
    
         @if (b1 != null)
        {
            @b1.AuthorName;   
        }
        else
        {
            <Strong>Book is Null</Strong>
        }
}
</div>

MVCAPPTAG/MVCAPPTAG/Views/Home/GetTime.cshtml
@{
    ViewData["Title"] = "GetTime";
}

<h1>Time: @ViewData["date"]</h1>
<div>
    <form action="GetTime">
        <input class="btn btn-danger" type="submit" value="⫷⫸" />
    </form>
</div>

MVCAPPTAG/MVCAPPTAG/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

    var parms = new Dictionary<string, string>
    {
        {"x","11"}
    };
    TempData["GlobalX"] = 100;
    TempData["GlobalY"] = 100;
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div>
    <div class="col-md-4">
        <form method="post" asp-all-route-data="parms">
            @*taghelper*@
            <div>
                @Html.Label("name")
                @Html.TextBox("name","Enter Name")
            </div>
            <div>
                @Html.Label("password")
                <input type = "password" name="password" placeholder="Enter Password"/>
            </div>
            <input type ="Submit" name="btnsubmit" value="HitMe"/>
        </form>
    </div>
</div>

MVCAPPTAG/MVCAPPTAG/Views/Home/IndexPost.cshtml
@{
    ViewData["Title"] = "IndexPost";
}

<h1>IndexPost</h1>
<div>
    <h3>ViewDataX: @ViewData["x"]</h3>
    <h3>TempDataX: @TempData["GlobalX"]</h3>
    <h3>ViewDataY: @ViewData["GlobalY"]</h3>
</div>

MVCAPPTAG/MVCAPPTAG/Views/Home/Menu.cshtml
<h1>Menu</h1>
<div class="text-center"><h1 class="display-4">Welcome</h1><div/>
<div class="jumbotron">
	<div>INR: &#8377</div>
		<a asp-action="Echo" asp-route-name="ORROOR" asp-route-city="OniGashima">Call Echo</a>
		<a asp-action="SayHello" asp-route-name="Ororroror">Call SayHello</a>
	</div>
<div/>

MVCAPPTAG/MVCAPPTAG/Views/Home/SayHello.cshtml
@{
    ViewData["Title"] = "SayHello";
}

<h1>SayHello</h1>

MVCAPPTAG/MVCAPPTAG/Views/PartialView/ChildList.cshtml
<div style=" background-color:cyan">
	<hr/>
	<h1>From Child View</h1>
	<ul>
		<li>Benz</li>
		<li>Innova</li>
		<li>Tesla M3</li>
	</ul>
	<hr/>
</div>

MVCAPPTAG/MVCAPPTAG/Views/PartialView/ChildViewData.cshtml
<div style="background-color:pink ">
	<h1>From ChildViewData View : @ViewData["data1"]</h1>
</div>

MVCAPPTAG/MVCAPPTAG/Views/PartialView/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div>
    @{
        var all_route_parms = new Dictionary<string, string>
        {
            {"x","200"},{"y","50"}
        };
    }
<h1>Index</h1>
    <div>
        <a asp-action="Add" asp-controller="Calculator" asp-route-x="258" asp-route-y="5">CallADD asp-route</a>
    </div>
    <div>
    <a asp-action="Add" asp-controller="Calculator" asp-all-route-data="all_route_parms">CallADD all_route_parms</a>
    </div>
@await Html.PartialAsync("ChildList")
<div/>

MVCAPPTAG/MVCAPPTAG/Views/PartialView/MyView.cshtml
<hr/>
<h1>Andhaman Beaches List</h1>
<ul>
	<li>RadhaNagar</li>
	<li>Neal Island</li>
	<li>Ross Island</li>
	<li>Wandoor</li>
</ul>
<hr/>

MVCAPPTAG/MVCAPPTAG/Views/PartialView/Score.cshtml
<div class="text-center">
	<h1>Score</h1>
	<h3>256 for 4 in 20 Over</h3>
</div>

MVCAPPTAG/MVCAPPTAG/Views/PartialView/Tabs.cshtml
@{
    ViewData["Title"] = "Tabs";
}
<h1>Tabs</h1>
<div>
    <!--Tab Buttons-->
    <ul id=" tabstrip "class=" nav nav-tabs" role="tablist">
        <li class=" active">
            <a href="#_FirstTab" role="tab" data-toggle="tab">Submission</a>
        </li>
        <li>
            <a href="#_SecondTab" role="tab" data-toggle="tab">Search</a>
        </li>
        <li>
            <a href="#_ThirdTab" role="tab" data-toggle="tab">Comments</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="_FirstTab">
            <Partial name="Score" />
        </div>
        <div class="tab-pane fade in active" id="_SecondTab">
            <Partial name="ChildList" />
        </div>
        <div class="tab-pane fade in active" id="_ThirdTab">
            <Partial name="ChildViewData" view-data="ViewData"/>
        </div>
    </div>
</div>
<Partial name="ChildViewData" view-data="ViewData" />
<Partial name="ChildList" />
<Partial name="Score" />

MVCAPPTAG/MVCAPPTAG/Views/Samlple/Start.cshtml
<div>
	Welcome to My Movies
</div>
<Partial name ="_MovieList"/>
<partial name ="_BookList"></>
@*@Html.PartialAsync("_MovieList");*@